---

dependencies: []

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Manage Squid proxy'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.4.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - squid
    - proxy
